release:
  enabled: true

docker:
  defaultTag: latest
  autoTags: [main, latest, next]

docs:
  location: /docs

  externalTypes:
    - corejslib/core
    - corejslib/result

  aliases:
    /api: https://raw.githubusercontent.com/corejslib/core/main/docs/api.md

  app:
    rpc:
      url: ws://whisper:81/api
